#!/bin/bash

export PATH=$HOME/.atuin/bin:$PATH

if no_command "atuin"; then
    curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
fi

if has_command "atuin"; then
    if is_bash; then
        eval "$(atuin init bash)"
        atuin import bash
    elif is_zsh; then
        eval "$(atuin init zsh)"
        atuin import zsh
    elif is_fish; then
        atuin init fish | source
        atuin import fish
    else
        echo "Mise: setup not called"
    fi
fi

