#!/bin/env bash

# set bash into vim mode
set -o vi

alias docker-compose="docker compose"
alias copy-buffer="xclip -selection clipboard"
alias paste-buffer="xclip -selection clipboard -o"

export LANG=en_US.UTF-8

export DOTFILES="$Dotfiles"

# load functions first
source $DOTFILES/shell/load_functions

# then others

username=$(whoami)
secret_dir="$Dotfiles/shell/secrets/${username}"
if [ -d "$secret_dir" ]; then
  for dir_file in $secret_dir/*; do
    echo "sourcing $dir_file"
    source "${dir_file}"
  done
fi

# must always be the first which means you
# don't use the path within the shell/functions
# as they need to be first to prepare
# custom functions we want to use.
source $Dotfiles/shell/load_paths

source $Dotfiles/shell/load_clauderc
source $Dotfiles/shell/load_zellij
source $Dotfiles/shell/load_installer
source $Dotfiles/shell/load_autocomplete
source $Dotfiles/shell/load_systemd
source $Dotfiles/shell/load_brew
source $Dotfiles/shell/load_mised
source $Dotfiles/shell/load_symlinks
source $Dotfiles/shell/load_ghostty
source $Dotfiles/shell/load_gitcrypt
source $Dotfiles/shell/load_direnv
source $Dotfiles/shell/load_zoxide
source $Dotfiles/shell/load_fzfd
source $Dotfiles/shell/load_jj
source $Dotfiles/shell/load_alias
source $Dotfiles/shell/load_omakub
source $Dotfiles/shell/load_neovim
source $Dotfiles/shell/load_dotnet
source $Dotfiles/shell/load_sops
source $Dotfiles/shell/load_exits
source $Dotfiles/shell/load_ca
source $Dotfiles/shell/load_tmux
source $Dotfiles/shell/load_cargo
source $Dotfiles/shell/load_deno
source $Dotfiles/shell/load_ssh
source $Dotfiles/shell/load_sha
source $Dotfiles/shell/load_golang
source $Dotfiles/shell/load_git
source $Dotfiles/shell/load_kubectl
source $Dotfiles/shell/load_net
source $Dotfiles/shell/load_android
source $Dotfiles/shell/load_docker
source $Dotfiles/shell/load_microk8s
source $Dotfiles/shell/load_python
source $Dotfiles/shell/load_flutter
source $Dotfiles/shell/load_sdkman
source $Dotfiles/shell/load_ssh_agent
source $Dotfiles/shell/load_ansible
source $Dotfiles/shell/load_nodejs
source $Dotfiles/shell/load_rust
source $Dotfiles/shell/load_wasm
source $Dotfiles/shell/load_youtube
source $Dotfiles/shell/load_nvidia
source $Dotfiles/shell/load_gnome_hotkeys
source $Dotfiles/shell/load_aider
source $Dotfiles/shell/load_vscode
source $Dotfiles/shell/load_zed

# bash completion
source $Dotfiles/shell/load_bash_completions
