#!/bin/bash

install_files=$Dotfiles/installers


install_one(){
    if is_ubuntu; then
        location="$install_files/ubuntu/$1.sh"
        if [ -e $location ]; then
            name=$(basename "$location")
            echo "Executing script: ${name} from $location"
            . $location
            exit 0
        fi
        location="$install_files/every/$1.sh"
        if [ -e $location ]; then
            name=$(basename "$location")
            echo "Executing script: ${name} from $location"
            . $location
        fi
    fi
    if is_archlinux; then
        location="$install_files/archlinux/$1.sh"
        if [ -e $location ]; then
            name=$(basename "$location")
            echo "Executing script: ${name} from $location"
            . $location
            exit 0
        fi
        location="$install_files/every/$1.sh"
        if [ -e $location ]; then
            name=$(basename "$location")
            echo "Executing script: ${name} from $location"
            . $location
        fi
    fi
    if is_mac; then
        echo "Not yet supported or setup"
    fi
}


install_all(){
    if is_ubuntu; then
        location="$install_files/ubuntu/$1"
        if [ -d $location ]; then 
            for f in "$location"/*.sh; do
            name=$(basename "$f")
            echo "Executing script: ${name}"
            . $f
            done
            exit 0
        fi
        location="$install_files/every/$1"
        if [ -d $location ]; then 
            for f in "$location"/*.sh; do
                name=$(basename "$f")
                echo "Executing script: ${name}"
                . $f
            done
        fi
    fi
    if is_archlinux; then
        location="$install_files/archlinux/$1"
        if [ -d $location ]; then 
            for f in "$location"/*.sh; do
            name=$(basename "$f")
            echo "Executing script: ${name}"
            . $f
            done
            exit 0
        fi
        location="$install_files/every/$1"
        if [ -d $location ]; then 
            for f in "$location"/*.sh; do
                name=$(basename "$f")
                echo "Executing script: ${name}"
                . $f
            done
        fi
    fi
    if is_mac; then
        echo "Not yet supported or setup"
    fi
}



