#!/bin/bash

export ZED_CONFIG_DIRECTORY="$HOME/.config/zed"
if is_mac; then
  export ZED_DIRECTORY="$HOME/Library/Application Support/zed"
else
  export ZED_DIRECTORY="$HOME/.config/zed"
fi

mkdir -p "$ZED_CONFIG_DIRECTORY"
mkdir -p "$ZED_DIRECTORY"

if no_symlink "$ZED_DIRECTORY/settings.json"; then
  ln -s "$Dotfiles/config/zed/settings.json" "$ZED_DIRECTORY/settings.json"
  ln -s "$Dotfiles/config/zed/settings.json" "$ZED_CONFIG_DIRECTORY/settings.json"
fi

if no_symlink "$ZED_DIRECTORY/keymap.json"; then
  ln -s "$Dotfiles/config/zed/keymap.json" "$ZED_DIRECTORY/keymap.json"
  ln -s "$Dotfiles/config/zed/keymap.json" "$ZED_CONFIG_DIRECTORY/keymap.json"
fi

if no_symlink "$ZED_CONFIG_DIRECTORY/settings.json"; then
  ln -s "$Dotfiles/config/zed/settings.json" "$ZED_CONFIG_DIRECTORY/settings.json"
fi

if no_symlink "$ZED_CONFIG_DIRECTORY/keymap.json"; then
  ln -s "$Dotfiles/config/zed/keymap.json" "$ZED_CONFIG_DIRECTORY/keymap.json"
fi

