#!/bin/bash

if has_command "cargo"; then
    if no_command "zellij"; then
        # bash <(curl -L https://zellij.dev/launch)
        cargo install --locked zellij
    fi
fi


if [ ! -h "$HOME/.config/zellij" ]; then
  ln -nsf "$Dotfiles/config/zellij" "$HOME/.config/zellij"
fi

zellij_ewe(){
    zellij attach -c ewetumo-development
}

zellij_talstack_1(){
    zellij attach -c talkstack-development-1
}

zellij_talstack_2(){
    zellij attach -c talkstack-development-2
}

