#!/bin/bash

sub_adder="--write-auto-subs --write-subs --sub-lang en --convert-subs srt --sub-format txt"

pyoutube_audio(){
    yt-dlp --remote-components ejs:npm --js-runtimes deno --socket-timeout $socket_timeout --retries infinite -ic -o "./audios/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist --extract-audio --audio-format mp3 --audio-quality 0 $@
}

pyoutube_split_audio(){
    yt-dlp --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout --split-chapters  --retries infinite -ic -o "./audios/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist --extract-audio --split-chapters --audio-format mp3 --audio-quality 0 $@
}

pyoutube(){
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout --retries infinite --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist $@
}

pyoutube_best(){
   yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout -f best --retries infinite --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist $@
}

pyoutube720(){
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout --retries infinite -f "bestvideo[height=720]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist $@
}

pyoutube360(){
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout --retries infinite -f "bestvideo[height=360]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist $@
}


youtube_audio(){
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --socket-timeout $socket_timeout --retries infinite -ic -o "./%(title)s.%(ext)s" --extract-audio --audio-format mp3 --audio-quality 0 $@
}

youtube() {
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --retries infinite $@
}

youtube720() {
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --retries infinite -f "bestvideo[height=720]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(title)s.%(ext)s" $@
}

youtube360(){
    yt-dlp $sub_adder --js-runtimes deno --remote-components ejs:npm --retries infinite -f "bestvideo[height=360]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(title)s.%(ext)s" $@
}

yt(){
    yt-dlp $sub_adder --retries infinite --ignore-errors -o "$2.mp4" "$1"
}

yt_silent(){
    file_name="$1"
    shift
    yt-dlp --retries infinite --ignore-errors -o "${file_name}.mp4" "$@" > /dev/null &
}

alias yts=yt_silent
