#!/bin/sh

test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if [[ -d /home/linuxbrew/.linuxbrew ]]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"
	eval "\$($(brew --prefix)/bin/brew shellenv)"
fi

# NOTE: package name must come FIRST, extra brew flags after
#       e.g. check_and_install llvm --yes  (NOT check_and_install --yes llvm)
check_and_install() {
	target_package="$1"
	shift

	if ! brew --prefix --installed "$target_package" &>/dev/null; then
		echo "Executing: brew install '$target_package' $*"
		brew install "$target_package" "$@"
	fi
}

check_and_install llvm --yes
check_and_install libpq --yes
check_and_install protobuf --yes
check_and_install snappy --yes
