#!/bin/env bash

source $DOTFILES/shell/functions

export RUST_BACKTRACE=full
# export RUSTFLAGS="-Z threads=10 -Zproc-macro-backtrace -Zmacro-backtrace"
# `RUSTFLAGS="-Zmacro-backtrace"`

enable_rust_backtrace(){
    export RUSTFLAGS="-Z threads=10 -Zproc-macro-backtrace -Zmacro-backtrace"
}

disable_rust_backtrace(){
    unset RUSTFLAGS
}

if no_command rust; then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	brew install mold llvm gcc
fi

if no_command wget; then
    if is_archlinux; then
        if has_command yay; then
            yay -Sy wget
        else
            sudo pacman -Sy --noconfirm wget
        fi
    fi
fi

if no_command rust-analyzer; then
    mkdir -p ~/.local/bin
    wget -O $HOME/.local/bin/rust-analyzer.gz https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz
    gunzip ~/.local/bin/rust-analyzer.gz
    chmod +x ~/.local/bin/rust-analyzer
fi

export PATH=$HOME/.local/bin:/usr/lib/rustup/bin:$PATH

. "$HOME/.cargo/env"
