#!/bin/bash

if [[ ! -h $HOME/.local/bin/run-command ]]; then
  ln -s $DOTFILES/bin/run-command $HOME/.local/bin/launch-webapp
fi

if [[ ! -h $HOME/.local/bin/run-command ]]; then
  ln -s $DOTFILES/bin/run-command $HOME/.local/bin/run-command
fi

if [[ ! -h $HOME/.config/rust-analyzer ]]; then
  ln -s $DOTFILES/config/rust-analyzer $HOME/.config/rust-analyzer
fi


if [[ ! -h $HOME/.config/ashell ]]; then
  ln -s $DOTFILES/config/ashell $HOME/.config/ashell
fi

if [[ ! -h $HOME/.config/bacon ]]; then
  ln -s $DOTFILES/config/bacon $HOME/.config/bacon
fi

if [[ ! -h $HOME/.config/ghostty ]]; then
  ln -s $DOTFILES/config/ghostty $HOME/.config/ghostty
fi

if [[ ! -h $HOME/.claude/settings.json ]]; then
  mkdir -p $HOME/.claude
  ln -s $DOTFILES/config/claude/settings.json $HOME/.claude/settings.json
fi

if [[ ! -h $HOME/.local/share/applications ]]; then
  mkdir -p $HOME/.local/share/
  ln -s $DOTFILES/applications $HOME/.local/share/applications
fi

if [[ ! -h $HOME/.config/walker ]]; then
  ln -s $DOTFILES/config/walker $HOME/.config/walker
fi

if [[ ! -h $HOME/.config/elephant ]]; then
  ln -s $DOTFILES/config/elephant $HOME/.config/elephant
fi

if [[ ! -h $HOME/.config/systemd ]]; then
  # ln -s $DOTFILES/systemd $HOME/.config/systemd
  mkdir -p $HOME/.config/systemd
  \cp -u -r -f $DOTFILES/config/systemd/user $HOME/.config/systemd/user
fi

if [[ ! -h $HOME/.config/Typora ]]; then
  ln -s $DOTFILES/config/Typora $HOME/.config/Typora
fi

if [[ ! -h $HOME/.config/waybar ]]; then
  ln -s $DOTFILES/config/waybar $HOME/.config/waybar
fi

if [[ ! -h $HOME/.config/wofi ]]; then
  ln -s $DOTFILES/config/wofi $HOME/.config/wofi
fi

if [[ ! -h $HOME/.config/yay ]]; then
  ln -s $DOTFILES/config/yay $HOME/.config/yay
fi

if [[ ! -h $HOME/.config/nautilus ]]; then
  ln -s $DOTFILES/config/nautilus $HOME/.config/nautilus
fi

if [[ ! -h $HOME/.config/kitty ]]; then
  ln -s $DOTFILES/config/kitty $HOME/.config/kitty
fi

if [[ ! -h $HOME/.config/fcitx5 ]]; then
  ln -s $DOTFILES/config/fcitx5 $HOME/.config/fcitx5
fi

if [[ ! -h $HOME/.config/fcitx ]]; then
  ln -s $DOTFILES/config/fcitx $HOME/.config/fcitx
fi

if [[ ! -h $HOME/.config/niri ]]; then
  ln -s $DOTFILES/config/niri $HOME/.config/niri
fi

if [[ ! -h $HOME/.config/fastfetch ]]; then
  ln -s $DOTFILES/config/fastfetch $HOME/.config/fastfetch
fi

if [[ ! -h $HOME/.config/alacritty ]]; then
  ln -s $DOTFILES/config/alacritty $HOME/.config/alacritty
fi

if [[ ! -h $HOME/.config/btop ]]; then
  ln -s $DOTFILES/config/btop $HOME/.config/btop
fi

if [[ ! -h $HOME/.config/environment.d ]]; then
  ln -s $DOTFILES/config/environment.d $HOME/.config/environment.d
fi

if [[ ! -h $HOME/.config/fontconfig ]]; then
  ln -s $DOTFILES/config/fontconfig $HOME/.config/fontconfig
fi

if [[ ! -h $HOME/.config/lazydocker ]]; then
  ln -s $DOTFILES/config/lazydocker $HOME/.config/lazydocker
fi

if [[ ! -h $HOME/.config/lazygit ]]; then
  ln -s $DOTFILES/config/lazygit $HOME/.config/lazygit
fi

if [[ ! -h $HOME/.config/xournalpp ]]; then
  ln -s $DOTFILES/config/xournalpp $HOME/.config/xournalpp
fi

if [[ ! -h $HOME/.config/wpaperd ]]; then
  ln -s $DOTFILES/config/wpaperd $HOME/.config/wpaperd
fi
