-- Generated by Palette Forge
return {
  {
    "folke/tokyonight.nvim",
    opts = {
      style = "night",
      on_colors = function(c)
        c.bg = "#181818"
        c.bg_dark = "#161615"
        c.bg_float = "#1F1F1F"
        c.bg_sidebar = "#161615"
        c.bg_statusline = "#161615"
        c.fg = "#E8E7E2"
        c.fg_dark = "#C2C0B4"
        c.fg_gutter = "#5d5c55"
        c.border = "#DA5E45"
        c.comment = "#706D5C"
        c.orange = "#FF7B63"
        c.yellow = "#E3B77D"
        c.red = "#CC0000"
        c.blue = "#81DFDF"
        c.cyan = "#64CBCF"
        c.green = "#61CD70"
        c.magenta = "#B98BEC"
      end,
      on_highlights = function(hl, c)
        hl.Normal = { bg = c.bg, fg = c.fg }
        hl.NonText = { fg = c.comment }
        hl.Comment = { fg = c.comment, italic = true }
        hl.LineNr = { fg = c.fg_gutter }
        hl.CursorLineNr = { fg = c.orange, bold = true }
        hl.CursorLine = { bg = "#1F1F1F" }
        hl.Visual = { bg = "#2A2925" }
        hl.StatusLine = { bg = c.bg_dark, fg = c.fg }
        hl.StatusLineNC = { bg = c.bg_dark, fg = c.comment }
        hl.WinSeparator = { fg = c.border }
        hl.TabLine = { bg = c.bg_dark, fg = c.comment }
        hl.TabLineSel = { bg = c.cyan, fg = c.bg }
        hl.TabLineFill = { bg = c.bg_dark }
        hl.DiagnosticWarn = { fg = c.yellow }
        hl.DiagnosticError = { fg = c.red }
        hl.DiagnosticInfo = { fg = c.cyan }
        hl.DiagnosticHint = { fg = c.magenta }
        hl.DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true }
        hl.DiagnosticUnderlineError = { sp = c.red, undercurl = true }
        hl.DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true }
        hl.DiagnosticUnderlineHint = { sp = c.magenta, undercurl = true }
        hl.Pmenu = { bg = "#161615", fg = c.fg_dark }
        hl.PmenuSel = { bg = c.cyan, fg = c.bg }
        hl.Search = { bg = c.orange, fg = c.bg }
        hl.IncSearch = { bg = c.yellow, fg = c.bg }
        hl.MatchParen = { fg = c.orange, bold = true }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "tokyonight" },
  },
}
