#!/bin/bash

sudo pacman -S --asdeps --needed flatpak

flatpak install -u -y flathub com.obsproject.Studio
flatpak install -u -y flathub com.obsproject.Studio.Plugin.OBSVkCapture
flatpak install -u -y flathub com.obsproject.Studio.Plugin.DroidCam
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Gstreamer
flatpak install -u -y flathub com.obsproject.Studio.Plugin.BackgroundRemoval
flatpak install -u -y flathub com.obsproject.Studio.Plugin.GStreamerVaapi 
flatpak install -u -y flathub com.obsproject.Studio.Plugin.DistroAV
flatpak install -u -y flathub com.obsproject.Studio.Plugin.AitumMultistream
flatpak install -u -y flathub com.obsproject.Studio.Plugin.WaylandHotkeys
flatpak install -u -y flathub com.obsproject.Studio.Plugin.SceneSwitcher
flatpak install -u -y flathub com.obsproject.Studio.Plugin.CompositeBlur
flatpak install -u -y flathub com.obsproject.Studio.Plugin.InputOverlay
flatpak install -u -y flathub com.obsproject.Studio.Plugin.AdvancedMasks
flatpak install -u -y flathub com.obsproject.Studio.Plugin.AudioMonitor
flatpak install -u -y flathub com.obsproject.Studio.Plugin.MoveTransition
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Countdown
flatpak install -u -y flathub com.obsproject.Studio.Plugin.waveform
flatpak install -u -y flathub com.obsproject.Studio.Plugin.SourceClone
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Draw
flatpak install -u -y flathub com.obsproject.Studio.Plugin._3DEffect
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Shaderfilter
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Teleport
flatpak install -u -y flathub com.obsproject.Studio.Plugin.SourceRecord
flatpak install -u -y flathub com.obsproject.Studio.Plugin.ScaleToSound
flatpak install -u -y flathub com.obsproject.Studio.Plugin.TransitionTable
flatpak install -u -y flathub com.obsproject.Studio.Plugin.MuteFilter
flatpak install -u -y flathub com.obsproject.Studio.Plugin.ColorMonitor
flatpak install -u -y flathub com.obsproject.Studio.Plugin.RecordRename
flatpak install -u -y flathub com.obsproject.Studio.Plugin.DownstreamKeyer
flatpak install -u -y flathub com.obsproject.Studio.Plugin.FreezeFilter
flatpak install -u -y flathub com.obsproject.Studio.Plugin.Ocr
flatpak install -u -y flathub com.obsproject.Studio.Plugin.GradientSource
flatpak install -u -y flathub com.obsproject.Studio.Plugin.OBSLivesplitOne
flatpak install -u -y flathub com.obsproject.Studio.Plugin.AsyncAudioFilter
flatpak install -u -y flathub com.obsproject.Studio.Plugin.TextPthread
flatpak install -u -y flathub com.github.johnfactotum.QuickLookup
flatpak install -u -y flathub xyz.ketok.Speedtest
flatpak install -u -y fflathub studio.planetpeanut.Bobby
flatpak install -u -y flathub org.gnome.Fractal
flatpak install -u -y flathub de.schmidhuberj.DieBahn
flatpak install -u -y flathub com.github.flxzt.rnote
flatpak install -u -y flathub io.github.shonebinu.Brief
flatpak install -u -y flathub io.github.alainm23.planify
flatpak install -u -y flathub com.google.Chrome
flatpak install -u -y flathub com.discordapp.Discord
flatpak install -u -y flathub org.vinegarhq.Sober
flatpak install -u -y flathub org.telegram.desktop
flatpak install -u -y flathub net.davidotek.pupgui2
flatpak install -u -y flathub com.protonvpn.www
flatpak install -u -y flathub org.localsend.localsend_app
flatpak install -u -y flathub org.kde.krita
flatpak install -u -y flathub org.kde.kdenlive
flatpak install -u -y flathub io.freetubeapp.FreeTube
flatpak install -u -y flathub org.kde.okular
flatpak install -u -y flathub ru.linux_gaming.PortProton
flatpak install -u -y flathub com.github.unrud.VideoDownloader
flatpak install -u -y flathub org.torproject.torbrowser-launcher
flatpak install -u -y flathub org.winehq.Wine
flatpak install -u -y flathub fr.handbrake.ghb
flatpak install -u -y flathub org.signal.Signal
flatpak install -u -y flathub us.zoom.Zoom
flatpak install -u -y flathub org.audacityteam.Audacity
flatpak install -u -y flathub io.gitlab.adhami3310.Impression
flatpak install -u -y flathub de.haeckerfelix.Shortwave
flatpak install -u -y flathub org.kde.kcalc
flatpak install -u -y flathub org.kde.gwenview
flatpak install -u -y flathub com.opera.Opera
flatpak install -u -y flathub com.github.jeromerobert.pdfarranger
flatpak install -u -y flathub org.openrgb.OpenRGB
flatpak install -u -y flathub io.github.jeffshee.Hidamari
flatpak install -u -y flathub org.kde.isoimagewriter
flatpak install -u -y flathub net.nokyan.Resources
flatpak install -u -y flathub io.github.thetumultuousunicornofdarkness.cpu-x
flatpak install -u -y flathub org.flameshot.Flameshot
flatpak install -u -y flathub tv.plex.PlexDesktop
flatpak install -u -y flathub com.dec05eba.gpu_screen_recorder
flatpak install -u -y flathub com.calibre_ebook.calibre
flatpak install -u -y flathub dev.edfloreshz.CosmicTweaks
flatpak install -u -y flathub io.dbeaver.DBeaverCommunity
flatpak install -u -y flathub com.google.AndroidStudio
flatpak install -u -y flathub org.gnome.Loupe
flatpak install -u -y flathub eu.betterbird.Betterbird
flatpak install -u -y flathub io.gitlab.theevilskeleton.Upscaler
flatpak install -u -y flathub io.github.wiiznokes.fan-control
flatpak install -u -y flathub org.gnome.baobab
flatpak install -u -y flathub com.github.xournalpp.xournalpp
flatpak install -u -y flathub com.adobe.Reader
flatpak install -u -y flathub org.virt_manager.virt-manager
flatpak install -u -y flathub io.github.aandrew_me.ytdn
flatpak install -u -y flathub io.mpv.Mpv
flatpak install -u -y flathub com.logseq.Logseq
flatpak install -u -y flathub io.github.pwr_solaar.solaar
flatpak install -u -y flathub org.gnome.SimpleScan
flatpak install -u -y flathub org.x.Warpinator
flatpak install -u -y flathub page.tesk.Refine
flatpak install -u -y flathub org.mozilla.vpn
flatpak install -u -y flathub org.gnome.Papers
flatpak install -u -y flathub org.openshot.OpenShot
flatpak install -u -y flathub com.github.rafostar.Clapper
flatpak install -u -y flathub io.github.giantpinkrobots.flatsweep
flatpak install -u -y flathub org.gnome.Firmware
flatpak install -u -y flathub com.gitlab.davem.ClamTk
flatpak install -u -y flathub org.ardour.Ardour
flatpak install -u -y flathub com.jgraph.drawio.desktop
flatpak install -u -y flathub org.angryip.ipscan
flatpak install -u -y flathub org.gnome.eog
flatpak install -u -y flathub org.stellarium.Stellarium
flatpak install -u -y flathub com.actualbudget.actual
flatpak install -u -y flathub org.kde.audiotube
flatpak install -u -y flathub org.avidemux.Avidemux
flatpak install -u -y flathub com.jetbrains.IntelliJ-IDEA-Ultimate
flatpak install -u -y flathub org.gnome.FileRoller
flatpak install -u -y flathub net.nymtech.NymVPN
flatpak install -u -y flathub com.dropbox.Client
flatpak install -u -y flathub com.warlordsoftwares.media-downloader
flatpak install -u -y flathub ca.parallel_launcher.ParallelLauncher
flatpak install -u -y flathub org.kde.minuet
flatpak install -u -y flathub com.notesnook.Notesnook
flatpak install -u -y flathub org.turbowarp.TurboWarp
flatpak install -u -y flathub com.github.taiko2k.tauonmb
