-- Smart "go to definition": a 3-tier fallback chain. LANGUAGE-AGNOSTIC.
--
-- Wired as `gd` for every LSP buffer (plugin-lspconfig.lua's global LspAttach),
-- so it works for any language server -- rust-analyzer, pyright, clangd, HLS,
-- etc. Tiers, tried in order:
--   1. LSP definition. If the server has one, open it through the SAME Telescope
--      picker the rest of the config uses (lsp_definitions).
--   2. ctags. If a tag exists for the symbol (on the buffer's &tags), open it
--      through the Telescope `tags` picker. Haskell tags are auto-generated by
--      fast-tags (plugin-haskell.lua); other languages just need any tags file.
--   3. Docs fallback (optional, per-filetype). If tiers 1-2 miss and a filetype
--      has registered a doc opener, call it -- e.g. Haskell opens the symbol's
--      Haddock/Hackage page via Hoogle (registered in plugin-haskell.lua). This
--      is the "the source isn't indexed anywhere, but I can still read the docs"
--      tier. Register with M.register_doc_fallback(filetype, fn).
--
-- With no registered doc fallback, tier 3 is skipped and you get a notification
-- -- i.e. for other languages it behaves exactly like the old `gd` until you
-- teach it a doc opener.

local M = {}

--- filetype -> function(word) that opens documentation for `word`.
M.doc_fallbacks = {}

--- Register a tier-3 documentation opener for a filetype (or list of them).
--- @param filetypes string|string[]
--- @param fn fun(word: string)
function M.register_doc_fallback(filetypes, fn)
  if type(filetypes) == "string" then
    filetypes = { filetypes }
  end
  for _, ft in ipairs(filetypes) do
    M.doc_fallbacks[ft] = fn
  end
end

--- Does an exact-match ctags entry exist for `word` on the current buffer's
--- &tags? (Synchronous; respects the buffer-local tag files we set for Haskell.)
local function has_exact_tag(word)
  local pat = "^" .. vim.fn.escape(word, [[\/.*$^~[]]) .. "$"
  local ok, matches = pcall(vim.fn.taglist, pat)
  return ok and type(matches) == "table" and not vim.tbl_isempty(matches)
end

--- Tier 2 -> 3: ctags if present, else the filetype's doc fallback.
local function tags_or_docs()
  local word = vim.fn.expand("<cword>")
  if word == "" then
    return
  end

  if has_exact_tag(word) then
    local ok, builtin = pcall(require, "telescope.builtin")
    if ok then
      -- Prefilter the picker to the symbol (single match lists, Enter jumps).
      builtin.tags({ default_text = word })
    else
      pcall(vim.cmd, "tjump " .. vim.fn.fnameescape(word))
    end
    return
  end

  local fallback = M.doc_fallbacks[vim.bo.filetype]
  if fallback then
    return fallback(word)
  end

  vim.notify("No LSP definition or tag for '" .. word .. "'", vim.log.levels.WARN, { title = "goto" })
end

--- Go to definition: LSP first, then ctags, then per-filetype docs.
function M.definition()
  local bufnr = vim.api.nvim_get_current_buf()
  local method = vim.lsp.protocol.Methods.textDocument_definition
  local clients = vim.lsp.get_clients({ bufnr = bufnr, method = method })

  if #clients == 0 then
    return tags_or_docs()
  end

  local params = vim.lsp.util.make_position_params(0, clients[1].offset_encoding)
  vim.lsp.buf_request_all(bufnr, method, params, function(results)
    local found = false
    for _, res in pairs(results) do
      local r = res.result
      if r and not (type(r) == "table" and vim.tbl_isempty(r)) then
        found = true
        break
      end
    end
    if found then
      -- Re-run through the shared picker so behavior/UI matches the rest of the
      -- config (single result jumps, multiple show the picker).
      local ok, builtin = pcall(require, "telescope.builtin")
      if ok then
        builtin.lsp_definitions()
      else
        vim.lsp.buf.definition()
      end
    else
      tags_or_docs()
    end
  end)
end

return M
